### ISSUE TITLE
怎么写文件下载接口

### ISSUE THREAD

**Issue by java0408** [a805748009/hxy-socket#1]
从所知案例中无从得知怎么传送文件，现在业务需要有接口提供下载文件

**Comment by a805748009** [comment]
直接在controller中返回NsRespone即可 。
案例：
@Post(uri = "/file")
    fun channelUserFollow(map: Map<String, String>, nsRespone: NsRespone): Any {
        return nsRespone.returnFile(filePath, "[FILENAME].txt")
    }
